((twod, k) => { if(window[k]) return; window[k] = true;(()=>{"use strict";function e(e,t){let n,o=!0;return"boolean"==typeof e?(o=e,n=t):n=e,bn((e=>{const t=Zt(_n.document);"interactive"==t||"complete"==t?(n&&n(),e()):wn.addEventListener("DOMContentLoaded",(()=>{n&&n(),e()}),Et({capture:o,once:!0}))}))}const t=e=>{const t=Object.call,n=t.bind(t),o=Object.assign,s=Object.getOwnPropertyDescriptor,r=e=>o({__proto__:null},e);return r({sourceWindow:e,cSO:r,F_c:n,F_a:Object.apply,F_b:Object.bind,F_tS:Function.toString,A_fE:[].forEach,A_so:[].some,
A_sh:[].shift,A_j:[].join,A_iO:[].indexOf,A_iA:Array.isArray,O_a:o,O_k:Object.keys,O_v:Object.values,O_dP:Object.defineProperties,O_dPy:Object.defineProperty,O_hOP:Object.hasOwnProperty,O_gOPN:Object.getOwnPropertyNames,O_gOPD:s,O_gOPDs:Object.getOwnPropertyDescriptors,O_gPO:Object.getPrototypeOf,O_tS:{}.toString,J_p:JSON.parse,J_s:JSON.stringify,M_f:Math.floor,M_r:Math.random,M_m:Math.max,M_mi:Math.min,N_tS:(0).toString,N_MSI:Number.MAX_SAFE_INTEGER,P_t:Promise.prototype.then,
P_c:Promise.prototype.catch,R_rABS:FileReader.prototype.readAsBinaryString,R_rAT:FileReader.prototype.readAsText,R_r:s(FileReader.prototype,"result").get,R_enq:e.ReadableStreamDefaultController?e.ReadableStreamDefaultController.prototype.enqueue:null,R_cl:e.ReadableStreamDefaultController?e.ReadableStreamDefaultController.prototype.close:null,S_fCC:String.fromCharCode,S_sl:"".slice,S_su:"".substr,S_sp_nr:"".split,S_iO:"".indexOf,S_tr:"".trim,S_r_nr:"".replace,S_rA_nr:"".replaceAll,
S_cCA:"".charCodeAt,S_tLC:"".toLowerCase,S_tUC:"".toUpperCase,Y_tST:Symbol.toStringTag,Y_unsc:Symbol.unscopables,USP_tS:URLSearchParams.prototype.toString,D_pFS:DOMParser.prototype.parseFromString,U_cOU:URL.createObjectURL,U_rOU:URL.revokeObjectURL,X_o:XMLHttpRequest.prototype.open,X_pSD:XMLHttpRequest.prototype.DONE,X_pSH:XMLHttpRequest.prototype.HEADERS_RECEIVED,X_pSL:XMLHttpRequest.prototype.LOADING,X_pSO:XMLHttpRequest.prototype.OPENED,X_pSU:XMLHttpRequest.prototype.UNSENT,
X_s:XMLHttpRequest.prototype.send,D_n:Date.now,I_tS:e=>""+e,E_r:Element.prototype.remove,E_s:Element.prototype.setAttribute,E_rA:Element.prototype.removeAttribute,D_cS:s(Document.prototype,"currentScript").get,D_gRS:s(Document.prototype,"readyState").get,D_cE:Document.prototype.createElementNS,D_gEBT:Document.prototype.getElementsByTagName,M_rT:s(MouseEvent.prototype,"relatedTarget").get,C_d:s(CustomEvent.prototype,"detail").get,C_pA:CustomEvent.prototype.AT_TARGET,
M_d:MutationObserver.prototype.disconnect,W_aEL:addEventListener,W_rEL:removeEventListener,parseInt,parseFloat,CustomEvent,CompositionEvent,KeyboardEvent,MouseEvent,MutationObserver,console:Object.assign({},console),Error,Uint8Array,Blob,ReadableStream,Number,String,Proxy,Window,FileReader,DOMParser,XMLHttpRequest,Function,RegExp,Promise,encodeURIComponent,decodeURIComponent,encodeURI,decodeURI,escape,unescape,atob,btoa,setTimeout,clearTimeout,setInterval,clearInterval,postMessage,dispatchEvent,
alert,prompt,confirm,close,getElementById:e.Document.prototype.getElementById,createEvent:e.Document.prototype.createEvent,createElement:e.Document.prototype.createElement})},n="vault"in twod;if(n&&void 0===twod.vault)throw"Invalid vault"
;const o=twod.vault=twod.vault||t(twod.unsafeWindow),{cSO:s,F_c:r,F_a:i,F_b:a,F_tS:c,A_fE:d,A_so:l,A_sh:u,A_j:p,A_iO:m,A_iA:g,O_a:f,O_k:_,O_v:h,O_dP:v,O_dPy:w,O_hOP:b,O_gOPN:y,O_gOPD:M,O_gOPDs:E,O_gPO:L,O_tS:S,J_p:I,J_s:O,M_f:x,M_r:R,M_m:j,M_mi:D,N_tS:P,N_MSI:C,P_t:$,P_c:A,R_rABS:T,R_rAT:U,R_r:k,R_enq:B,R_cl:F,S_fCC:X,S_sl:N,S_su:q,S_iO:W,S_sp_nr:H,S_tr:J,S_rA_nr:K,S_cCA:G,S_tLC:Y,S_tUC:z,Y_tST:V,Y_unsc:Z,D_pFS:Q,D_cS:ee,D_gRS:te,D_cE:ne,D_gEBT:oe,E_r:se,E_s:re,E_rA:ie,C_pA:ae,M_d:ce,C_d:de,M_rT:le,U_cOU:ue,U_rOU:pe,USP_tS:me,X_o:ge,X_s:fe,X_pSD:_e,X_pSH:he,X_pSL:ve,X_pSO:we,X_pSU:be,D_n:ye,I_tS:Me,W_aEL:Ee,W_rEL:Le,parseInt:Se,parseFloat:Ie,console:Oe,encodeURIComponent:xe,decodeURIComponent:Re,encodeURI:je,decodeURI:De,escape:Pe,unescape:Ce,atob:$e,btoa:Ae,postMessage:Te,dispatchEvent:Ue,alert:ke,prompt:Be,confirm:Fe,close:Xe,getElementById:Ne,createEvent:qe,createElement:We,CustomEvent:He,CompositionEvent:Je,KeyboardEvent:Ke,MouseEvent:Ge,MutationObserver:Ye,Uint8Array:ze,FileReader:Ve,DOMParser:Ze,XMLHttpRequest:Qe,Function:et,RegExp:tt,Promise:nt,Blob:ot,ReadableStream:st,Number:rt,String:it,Proxy:at,Window:ct}=o,dt=r,lt=i,ut=_,pt=h,mt=f,gt=w,ft=y,_t=M,ht=L,vt=g,wt=R,bt=j,yt=D,Mt=(e,t,n)=>dt(lt,e,t,n),Et=s,Lt=(e,t,n)=>(gt(e,t,Et({
value:n,configurable:!0,enumerable:!0,writable:!0})),e),St=(e,t)=>{const n=_t(e,t);return n?Et(n).value:void 0},It=(e,t)=>{const n=(e,t,o)=>{const s=_t(e,t),r=s?Et(s):void 0;let i;return r?r.enumerable?r.value:void 0:--o>=0&&(i=ht(e))?n(i,t,o):void 0};return n(e,t,5)},Ot=e=>{const t=(t,...n)=>Mt(e,t,n);return Lt(t,"wrappedJSObject",e),t},xt=()=>e=>Ot(e),Rt=Ot(a),jt=I,Dt=xt()(l),Pt=xt()(u),Ct=(e,t,n)=>{const o=e.length;let s=t||0;if(s>=o)return[];s<0&&(s=bt(0,o+s));let r=void 0===n?o:n
;r<0&&(r=bt(0,o+r)),r>o&&(r=o);const i=Et({});for(let t=s;t<r;t++)i[t]=St(e,t);return pt(i)},$t=xt()(p),At=(e,t)=>{let n=e.length||0;return Lt(e,n,t),n++,e.length=n},Tt=xt()(m),Ut=xt()(d),kt=xt()(b),Bt=xt()(H),Ft=xt()(N),Xt=Ot(S),Nt=ht({}),qt=e=>{const t=Et(e),n=ft(t);for(let e=0;e<n.length;e++){const o=n[e],s=t[o];null!==s&&"object"==typeof s&&ht(s)===Nt&&(t[o]=qt(s))}return t},Wt=xt()(c),Ht=xt()(P),Jt=xt()($),Kt=(xt()(A),xt()(T),xt()(U),xt()(k),B&&xt()(B),F&&xt()(F),
X),Gt=xt()(q),Yt=xt()(W),zt=(xt()(J),xt()(K||function(e,t){return $t(Bt(this,e),t)}),xt()(G)),Vt=xt()(Y),Zt=(xt()(z),Ot(Q),Ot(ee),Ot(te)),Qt=Ot(ne),en=Ot(oe),tn=(Ot(se),Ot(re),Ot(ie),Ot(le)),nn=Ot(de),on=ce?xt()(ce):ce,sn=pe,rn=(Ot(me),xt()(ge),xt()(fe),ye),an=He,cn=Ge,dn=ze,ln=Ye,un=ot,pn=function(e,t){return St(e,t)},mn=Et({addEventListener:!1,Array:!0,Blob:!0,close:!1,CustomEvent:!0,Date:!0,DOMParser:!0,Error:!0,Event:!0,FileReader:!0,KeyboardEvent:!0,location:!0,Math:!0,MouseEvent:!0,
Number:!0,Object:!0,Promise:!0,ReadableStream:!0,removeEventListener:!1,Uint8Array:!0,XMLHttpRequest:!0}),gn=((()=>{const e=Et({getElementById:Ne,createEvent:qe,createElement:We,dispatchEvent:Ue,addEventListener,removeEventListener}),t=Et({});Ut(ut(e),(n=>{try{const o=e[n];t[n]=function(...e){return Mt(o,_n.document,e)}}catch(e){t[n]=((e,t)=>{if(vn.error(`Tampermonkey sandbox preparation ${t?"("+t+") ":""}failed. This usually is caused by a third-party extension.`,e),t)return()=>{}
})(e,`document.${n}`)}}))})(),Et({top:!0,location:!0})),fn=twod,{unsafeWindow:_n,unsafeThis:hn}=fn;twod.bridges=twod.bridges||Et({});const vn=twod.console=twod.console||Et({}),wn=Et({addEventListener:Rt(Ee,_n),removeEventListener:Rt(Le,_n)});Ut(ut(gn),(async e=>{if(!wn[e])try{const t=_n[e];if(null==t)return;wn[e]=t}catch(e){}})),Ut(ut(mn),(async e=>{if(!wn[e])try{let t=St(_n,e);if(void 0===t&&(hn===_n||void 0===(t=St(hn,e))))return;const n=mn[e];wn[e]=!1===n&&"function"==typeof t?Rt(t,hn):t
}catch(e){}}));const bn=e=>{let t,n=[],o=!1;e((e=>{if(!o){if(n.length){const t=n;n=[],Ut(t,(t=>t(e)))}else t=e;o=!0}}));const s=Et({then:e=>(o?e(t):At(n,e),s)});return s},yn=()=>Ht(rn()+19831206*wt()+1,36),Mn=(()=>{const{console:e,bridges:t}=twod,n=Et({});let o;const s=(t,o,s,i)=>{let a,c=[],d=[],l=[],u=[];const p=()=>{d=[],l=[],u=[],_(),y=null,delete n[o]},m=e=>{t.send("port.message",Et({response_id:o,value:e}))},g=e=>{i&&"messageId"in e&&At(c,e),m(e)},f=(e,t=!0)=>{a=e,t&&m(e)},_=()=>{a=void 0
},h=Et({addListener:e=>{At(d,e)}}),v=Et({addListener:e=>{At(l,e)}}),w=Et({addListener:e=>{At(u,e)}}),b=()=>{p(),t.send("port.message",Et({response_id:o,disconnect:!0}))};let y=Et(s?{postMessage:g,connectMessage:f,stopReconnecting:_,onMessage:h,onDisconnect:v,onReconnect:w,disconnect:b}:{postMessage:g,onMessage:h,onDisconnect:v,disconnect:b});return n[o]=Et({message:t=>{if(i&&(e=>"ack"in e)(t)){const{messageId:n}=t;(t=>{if(!t)return void e.warn("PortMessaging: no message id in ack message")
;if(a&&a.messageId===t)return;let n=-1;Dt(c,((e,o)=>e.messageId===t&&(n=o,!0))),-1!==n?(Ut(Ct(c,0,n),(t=>e.warn(`PortMessaging: message ${t.messageId} was not ack'ed!`,t))),c=Ct(c,n+1)):e.warn(`PortMessaging: no one is waiting for ${t}`)})(n)}d&&Ut(d,(e=>e(t)))},disconnect:()=>{if(a&&s)return r(s,o),f(a),i&&Ut(c,(e=>m(e))),void(u&&Ut(u,(e=>e())));l&&Ut(l,(e=>e())),p()}}),y},r=(e,n)=>{t.first.send("port.message",Et({response_id:n,connect:!0,destination:e}))};return Et({message:(t,r)=>{let i
;if(t.connect){if(!t.destination||!t.response_id)throw"invalid message";o&&o(t.destination,s(r,t.response_id))}else{if(!t.response_id)throw"invalid message";if(!(i=n[t.response_id]))return void e.warn("ports: unknown id",t.response_id,t);t.disconnect?i.disconnect():i.message(t.value)}},connect:function(e,n,o){const i=yn();return r(e,i),s(t.first,i,n?e:void 0,o)},onConnect:Et({addListener:e=>{o=e}})})
})(),{setInterval:En,setTimeout:Ln,clearInterval:Sn,clearTimeout:In,console:On,cloneInto:xn,exportFunction:Rn,createObjectIn:jn}=_n,Dn=Object.assign({},On),Pn=En.bind(_n),Cn=Ln.bind(_n),$n=Sn.bind(_n),An=(In.bind(_n),hn==_n.top),{arrayBuffer:Tn,blob:Un}=_n.Response.prototype,{arrayBuffer:kn}=_n.Blob.prototype,{then:Bn}=_n.Promise.prototype,{fetch:Fn,location:Xn,document:Nn,Response:qn}=_n,Wn=Ot(Tn),Hn=Ot(Un),Jn=Ot(kn),Kn=xn,Gn=Et({encode:e=>Ce(xe(e)),decode:e=>Re(Pe(e))}),Yn=(Et({encode:e=>{
let t="";for(let n=0;n<e.length;n++)t+=Kt(255&zt(e,n));return Ae(t)},decode:e=>$e(e)}),(e,t)=>{const n=(e,t)=>e<<t|e>>>32-t,o=(e,t)=>{const n=2147483648&e,o=2147483648&t,s=1073741824&e,r=1073741824&t,i=(1073741823&e)+(1073741823&t);return s&r?2147483648^i^n^o:s|r?1073741824&i?3221225472^i^n^o:1073741824^i^n^o:i^n^o},s=(e,t,s,r,i,a,c)=>(e=o(e,o(o(((e,t,n)=>e&t|~e&n)(t,s,r),i),c)),o(n(e,a),t)),r=(e,t,s,r,i,a,c)=>(e=o(e,o(o(((e,t,n)=>e&n|t&~n)(t,s,r),i),c)),
o(n(e,a),t)),i=(e,t,s,r,i,a,c)=>(e=o(e,o(o(((e,t,n)=>e^t^n)(t,s,r),i),c)),o(n(e,a),t)),a=(e,t,s,r,i,a,c)=>(e=o(e,o(o(((e,t,n)=>t^(e|~n))(t,s,r),i),c)),o(n(e,a),t)),c=e=>{let t,n,o="",s="";for(n=0;n<=3;n++)t=e>>>8*n&255,s="0"+Ht(t,16),o+=Gt(s,s.length-2,2);return o};let d,l,u,p,m,g,f,_;t&&"utf-8"==Vt(t)&&(e=Gn.encode(e));const h=(e=>{let t;const n=e.length,o=n+8,s=16*((o-o%64)/64+1),r=[];for(let e=0;e<=s-1;e++)At(r,0);let i=0,a=0;for(;a<n;)t=(a-a%4)/4,i=a%4*8,r[t]=r[t]|zt(e,a)<<i,a++
;return t=(a-a%4)/4,i=a%4*8,r[t]=r[t]|128<<i,r[s-2]=n<<3,r[s-1]=n>>>29,r})(e);m=1732584193,g=4023233417,f=2562383102,_=271733878;for(let e=0;e<h.length;e+=16)d=m,l=g,u=f,p=_,m=s(m,g,f,_,h[e+0],7,3614090360),_=s(_,m,g,f,h[e+1],12,3905402710),f=s(f,_,m,g,h[e+2],17,606105819),g=s(g,f,_,m,h[e+3],22,3250441966),m=s(m,g,f,_,h[e+4],7,4118548399),_=s(_,m,g,f,h[e+5],12,1200080426),f=s(f,_,m,g,h[e+6],17,2821735955),g=s(g,f,_,m,h[e+7],22,4249261313),m=s(m,g,f,_,h[e+8],7,1770035416),
_=s(_,m,g,f,h[e+9],12,2336552879),f=s(f,_,m,g,h[e+10],17,4294925233),g=s(g,f,_,m,h[e+11],22,2304563134),m=s(m,g,f,_,h[e+12],7,1804603682),_=s(_,m,g,f,h[e+13],12,4254626195),f=s(f,_,m,g,h[e+14],17,2792965006),g=s(g,f,_,m,h[e+15],22,1236535329),m=r(m,g,f,_,h[e+1],5,4129170786),_=r(_,m,g,f,h[e+6],9,3225465664),f=r(f,_,m,g,h[e+11],14,643717713),g=r(g,f,_,m,h[e+0],20,3921069994),m=r(m,g,f,_,h[e+5],5,3593408605),_=r(_,m,g,f,h[e+10],9,38016083),f=r(f,_,m,g,h[e+15],14,3634488961),
g=r(g,f,_,m,h[e+4],20,3889429448),m=r(m,g,f,_,h[e+9],5,568446438),_=r(_,m,g,f,h[e+14],9,3275163606),f=r(f,_,m,g,h[e+3],14,4107603335),g=r(g,f,_,m,h[e+8],20,1163531501),m=r(m,g,f,_,h[e+13],5,2850285829),_=r(_,m,g,f,h[e+2],9,4243563512),f=r(f,_,m,g,h[e+7],14,1735328473),g=r(g,f,_,m,h[e+12],20,2368359562),m=i(m,g,f,_,h[e+5],4,4294588738),_=i(_,m,g,f,h[e+8],11,2272392833),f=i(f,_,m,g,h[e+11],16,1839030562),g=i(g,f,_,m,h[e+14],23,4259657740),m=i(m,g,f,_,h[e+1],4,2763975236),
_=i(_,m,g,f,h[e+4],11,1272893353),f=i(f,_,m,g,h[e+7],16,4139469664),g=i(g,f,_,m,h[e+10],23,3200236656),m=i(m,g,f,_,h[e+13],4,681279174),_=i(_,m,g,f,h[e+0],11,3936430074),f=i(f,_,m,g,h[e+3],16,3572445317),g=i(g,f,_,m,h[e+6],23,76029189),m=i(m,g,f,_,h[e+9],4,3654602809),_=i(_,m,g,f,h[e+12],11,3873151461),f=i(f,_,m,g,h[e+15],16,530742520),g=i(g,f,_,m,h[e+2],23,3299628645),m=a(m,g,f,_,h[e+0],6,4096336452),_=a(_,m,g,f,h[e+7],10,1126891415),f=a(f,_,m,g,h[e+14],15,2878612391),
g=a(g,f,_,m,h[e+5],21,4237533241),m=a(m,g,f,_,h[e+12],6,1700485571),_=a(_,m,g,f,h[e+3],10,2399980690),f=a(f,_,m,g,h[e+10],15,4293915773),g=a(g,f,_,m,h[e+1],21,2240044497),m=a(m,g,f,_,h[e+8],6,1873313359),_=a(_,m,g,f,h[e+15],10,4264355552),f=a(f,_,m,g,h[e+6],15,2734768916),g=a(g,f,_,m,h[e+13],21,1309151649),m=a(m,g,f,_,h[e+4],6,4149444226),_=a(_,m,g,f,h[e+11],10,3174756917),f=a(f,_,m,g,h[e+2],15,718787259),g=a(g,f,_,m,h[e+9],21,3951481745),m=o(m,d),g=o(g,l),f=o(f,u),_=o(_,p)
;const v=c(m)+c(g)+c(f)+c(_);return Vt(v)}),zn=(e,t)=>{const n=Qt(_n.document,"http://www.w3.org/1999/xhtml",e);return"string"==typeof t?n.append(t):t&&Ut(ut(t),(e=>{"textContent"==e?n.textContent=t[e]:n.setAttribute(e,t[e])})),n},Vn=t=>{const n=_n.document;if(n.body||"text/xml"==n.contentType)t();else{let n=!1;const o=new ln((()=>{n=!0,Vn(t),(on||(e=>e.disconnect()))(o)}));o.observe(_n.document,Et({childList:!0})),e((()=>{n||((on||(e=>e.disconnect()))(o),t())}))}},Zn=t=>{e((()=>{Cn((()=>t()),1)
}))};let Qn,eo;const to=Xn.host,no=e=>{"n:"==Gt(e,0,2)?Qn=Gt(e,2):e&&(eo=Gt(e,2))},oo=()=>Qn||(eo?(Qn=Yn(`${to}#${eo}`),Qn):void 0),so=e=>void 0!==St(e,"objUrl"),ro=e=>void 0!==St(e,"blob"),io=e=>void 0!==St(e,"dataUri"),ao=e=>void 0!==e.binary,co=["chrome"],lo=globalThis,{chrome:uo,browser:po}=lo;let mo,go,fo,_o;fo=()=>{if(void 0!==mo)return mo;try{const e=navigator.userAgent.match(/Chrom(e|ium)\/([0-9]+)\./);e&&(mo=parseInt(e[2]))}catch(e){}return mo},_o=()=>{if(void 0!==go)return go;try{
go=-1!=navigator.userAgent.search(/Android|Mobile/)}catch(e){}return go},fo();const ho=["chrome-extension:"];[].concat(["chrome"]);const vo=(()=>{const e={getInternalPathRegexp:function(e,t){const n=new RegExp("(\\"+["/",".","+","?","|","(",")","[","]","{","}","\\"].join("|\\")+")","g"),o=ho[0]+"//"+vo.id+"/";return new RegExp(o.replace(n,"\\$1")+"([a-zA-Z"+(e?"\\/":"")+"]*)"+(t||"").replace(n,"\\$1"))},getInternalPageRegexp:function(){return vo.getInternalPathRegexp(!1,".html")},
getPlatformInfo:e=>uo.runtime.getPlatformInfo(e),getBrowserInfo:e=>{e({name:"Chrome",version:`${fo()}`,vendor:"unknown"})}};return Object.defineProperty(e,"lastError",{get:()=>uo.runtime.lastError,enumerable:!0}),Object.defineProperty(e,"id",{get:()=>uo.runtime.id,enumerable:!0}),Object.defineProperty(e,"short_id",{get:()=>e.id.replace(/[^0-9a-zA-Z]/g,"").substr(0,4),enumerable:!0}),e})(),wo=(()=>{let e;return Object.defineProperties({},{inIncognitoContext:{
get:()=>(void 0===e&&(e=uo.extension.inIncognitoContext),e),set:t=>{e=t},enumerable:!0},...Object.getOwnPropertyDescriptors({getURL:function(e){return uo.runtime.getURL(e)},sendMessage:(e,t)=>uo.runtime.sendMessage(e,t),onMessage:{addListener:e=>uo.runtime.onMessage.addListener(e)},connect:e=>uo.runtime.connect({name:e})})})})(),bo=uo.userScripts&&uo.userScripts.onBeforeScript?{supported:!0,onBeforeScript:{addListener:e=>uo.userScripts.onBeforeScript.addListener(e)}}:{supported:!1
},yo=({sendPrefix:e,listenPrefix:t,send:n,onMessage:o})=>{if(void 0===n||void 0===o)throw"invalid args";let s,r,i=1;const a=Et({}),c=Et({}),d=e=>{e&&(s=e)},l=e=>{const t=++i;return c[i]=e,t};o(((o,i)=>o==`${t}_${s}`?(t=>{const{m:o,r:i,a:d,n:l}=t;if(a[o]&&(Ut(a[o],(e=>e(d))),delete a[o]),"message.response"==o){if(null==i)throw"Invalid Message";((e,t)=>{let n;e&&(n=c[e])&&(n(t),delete c[e])})(i,d)}else if(r){const t=i?t=>{n(`${e}_${s}`,Et({m:"message.response",a:t,r:i}))}:()=>{};r(Et({method:o,
args:d,node:l}),t)}})(i):null));const u=Et({init:async e=>{s?d():d(e)},refresh:()=>null,switchId:e=>{s&&u.cleanup(),d(e)},send:(t,o,r,i)=>bn((a=>{let c,d;"function"!=typeof r&&null!==r?(c=r,d=i):d=r,n(`${e}_${s}`,Et({m:t,a:o,r:d?l(d):null,n:c})),a()})),sendToId:(t,o,s)=>{n(`${e}_${t}`,Et({m:o,a:s,r:null}))},once:(e,t)=>{a[e]||(a[e]=[]),At(a[e],t)},setMessageListener:e=>{r=e},cleanup:()=>null});return u},Mo=bo,Eo=bo.supported&&!_n.pagejs;let Lo;const So=(e,t)=>{try{Lo(e),t&&t()}catch(e){
t&&t(e.message||e)}},Io="u"+yn(),{bridges:Oo}=twod;let xo=[];const Ro=e=>{Mo.onBeforeScript.addListener((o=>{const s=(e,n)=>{Ut(t,(t=>t(e,n)))},r=e=>At(n,Et({listener:e,clone:o.export}));gt(o.global,"pagejs",Et({set:o.export((t=>{delete o.global.pagejs;const n=o.metadata,{modes:i,nonce:a}=n;if(a&&no(a),Ut(xo,(e=>e(t,n))),xo=[],i.js){const n=Et({unsafeWindow:o.global,unsafeThis:o.global.window,pageWindow:void 0,contextId:Io,fSend:s,fOnMessage:r,cloneInto:void 0,exportFunction:void 0})
;t(o.export(n)),Oo.js.sendToId(Io,"commid",Et({id:e}))}})),configurable:!0})),Lo=o.global.eval}));const t=[],n=[],o=(e,t)=>{Ut(n,(({listener:n,clone:o})=>n(e,o(t))))},s=e=>At(t,e);return Et({createBridge:()=>{const t=yo(Et({sendPrefix:"2S",listenPrefix:"2U",cloneInto:Kn,send:o,onMessage:s}));return t.init(e),t}})};let jo;const{console:Do}=twod,Po=e=>(e.details&&e.details.url,bn((async t=>{t(e)}))),Co=e=>{const t=wo.connect(e);if(!vo.lastError)return t},$o=Et({setInterval:e=>{let t
;e.onMessage.addListener((n=>{"setInterval"==n.method&&(t=Pn(e.postMessage,n.t))})),e.onDisconnect.addListener((()=>{t&&$n(t),t=null}))},registerMenuCommand:e=>{const t=Co("registerMenuCommand");t?(t.onMessage.addListener((t=>{if("ack"in t)e.postMessage(t);else{const{method:n,event:o}=t;e.postMessage(Et({method:n,event:o}))}})),t.onDisconnect.addListener((()=>{e.disconnect()})),e.onMessage.addListener((e=>{
const{messageId:n,name:o,uuid:s,accessKey:r,autoClose:i,title:a,id:c,createdAt:d}=e,l=$t([c,jo,s],"#");t.postMessage(Et({messageId:n,method:"registerMenuCommand",name:o,title:a,uuid:s,menuId:l,createdAt:d,accessKey:r,autoClose:i}))})),e.onDisconnect.addListener((()=>{t.disconnect()}))):Cn((()=>e.disconnect()),1)},notification:e=>{const t=Co("notification");t?(t.onMessage.addListener((t=>{e.postMessage(t)})),t.onDisconnect.addListener((()=>{e.disconnect()})),e.onMessage.addListener((e=>{
t.postMessage(e)})),e.onDisconnect.addListener((()=>{t.disconnect()}))):Cn((()=>e.disconnect()),1)},openInTab:e=>{const t=Co("openInTab");t?(t.onMessage.addListener((t=>{e.postMessage(t)})),t.onDisconnect.addListener((()=>{e.disconnect()})),e.onMessage.addListener((e=>{const{messageId:n}=e;if("method"in e){const{method:o}=e;if("openInTab"==o)if("url"in e){let o=e.url;const{active:s,loadInBackground:r,insert:i,incognito:a,setParent:c}="boolean"==typeof e.options||void 0===e.options?Et({
loadInBackground:e.options}):e.options,d=void 0===s?void 0!==r&&!r:s,l=void 0===i||i;o&&"//"==Gt(o,0,2)&&(o=Xn.protocol+o),t.postMessage(Et({messageId:n,method:"openInTab",details:Et({url:o,options:Et({active:!!d,insert:!!l,incognito:!!a,setParent:!a&&!!c})}),uuid:e.uuid}))}else t.postMessage(e);else Do.warn(`content: unknown method ${o}`)}else"name"in e?t.postMessage(Et({messageId:n,name:e.name})):"focus"in e?t.postMessage(Et({messageId:n,focus:!0})):"close"in e&&t.postMessage(Et({messageId:n,
close:!0}))})),e.onDisconnect.addListener((()=>{t.disconnect()}))):Cn((()=>e.disconnect()),1)},download:e=>{let t;const n=Co("download");n?(n.onMessage.addListener((t=>{e.postMessage(t)})),n.onDisconnect.addListener((()=>{e.disconnect(),t=!0})),e.onMessage.addListener((e=>{"cancel"in e?(t=!0,n.postMessage(Et({cancel:!0,id:jo,uuid:e.uuid}))):"details"in e?Po(e).then((e=>{if(t)return;let{url:o,...s}=e.details;n.postMessage(Et({messageId:e.messageId,method:"download",details:Et({...s,from:Et({url:o
})}),id:jo,uuid:e.uuid,location:Xn.href}))})):n.postMessage(Et({messageId:e.messageId,method:"download",uuid:e.uuid,id:e.id}))})),e.onDisconnect.addListener((()=>{n.disconnect()}))):Cn((()=>e.disconnect()),1)},webRequest:e=>{const t=Co("webRequest");t?(t.onMessage.addListener((t=>{e.postMessage(t)})),t.onDisconnect.addListener((()=>{e.disconnect()})),e.onMessage.addListener((e=>{const{messageId:n,rules:o,uuid:s}=e;t.postMessage(Et({messageId:n,method:"webRequest",rules:o,uuid:s}))})),
e.onDisconnect.addListener((()=>{t.disconnect()}))):Cn((()=>e.disconnect()),1)},xhr:e=>{let t,n;const o=[],s=async e=>{if(e&&At(o,e),n)await n,s();else{const e=Pt(o);e&&e()}},r=Co("xhr");r?(r.onMessage.addListener((t=>{"ack"in t?e.postMessage(t):s((()=>{const{onpartial:o,data:s,...r}=t;let i;if(o&&s){const{tfd:t}=s;if(t){const s=(e=>e&&(ro(e)||so(e)||io(e)||ao(e))?(e=>{let t,n,o,s,r;if(so(e))t=e.objUrl.url;else if(ro(e))n=e.blob;else if(io(e))o=e.dataUri;else{
if(!ao(e))throw"incompatible TransferableData";s=e.binary,r=e.type}return Et({toBlob:()=>bn((e=>{if(n)e(n);else if(t)try{Jt(Fn(t),(t=>{Jt(Hn(t),(t=>{e(t)}))}))}catch(t){e(void 0)}else if(o)e((e=>{let t;const n=Bt(e,","),o=pn(n,0),s=pn(n,1);t=-1!=Yt(o,"base64")?$e(s):Ce(s);const r=pn(Bt(o,":"),1),i=pn(Bt(r,";"),0);return new un([t],Et({type:i}))})(o));else{if(!s)throw"incompatible Transferable";{const t=(e=>{const t=new dn(e.length);for(let n=0;n<e.length;n++)t[n]=zt(e,n);return t.buffer})(s)
;e(new un([t],r?Et({type:r}):void 0))}}})),dispose:()=>{t&&sn(t),t=n=o=s=void 0}})})(e):void 0)(t);if(!s)return;return void(n=bn((async t=>{const a=()=>{n=null,t(),s&&s.dispose()};try{const t=await s.toBlob();if(!t)return void a();const n=t.type;let c;if(c="arrayBuffer"in t?await Jn(t):await Wn(new qn(t)),!c)return void a();i=Et({nada:Et({buffer:c,type:n})}),e.postMessage(Et({...r,onpartial:o,data:i})),a()}catch(e){Do.warn(e),a()}})))}i=s}else i=s;e.postMessage(Et({...r,onpartial:o,data:i}))}))
})),r.onDisconnect.addListener((()=>{s((async()=>{e.disconnect(),t=!0}))})),e.onMessage.addListener((e=>{Po(e).then((e=>{t||(e.location=Xn.href,r.postMessage(e))}))})),e.onDisconnect.addListener((()=>{r.disconnect()}))):Cn((()=>e.disconnect()),1)},onurlchange:e=>{const t=Co("onurlchange");if(!t)return void Cn((()=>e.disconnect()),1);let n=()=>{e.postMessage(Et({url:Xn.href}))};const o=()=>{n&&(wn.removeEventListener("hashchange",n),n=null)};wn.addEventListener("hashchange",n),
t.onMessage.addListener((t=>{e.postMessage(t)})),t.onDisconnect.addListener((()=>{e.disconnect(),o()})),e.onMessage.addListener((e=>{t.postMessage(e)})),e.onDisconnect.addListener((()=>{t.disconnect(),o()}))},values:e=>{const t=Co("values");t?(t.onMessage.addListener((t=>{e.postMessage(t)})),t.onDisconnect.addListener((()=>{e.disconnect()})),e.onMessage.addListener((e=>{t.postMessage(e)})),e.onDisconnect.addListener((()=>{t.disconnect()}))):Cn((()=>e.disconnect()),1)},backgroundControl:e=>{
const t=Co("backgroundControl");t?(t.onMessage.addListener((t=>{e.postMessage(t)})),t.onDisconnect.addListener((()=>{e.disconnect()})),e.onMessage.addListener((e=>{t.postMessage(e)})),e.onDisconnect.addListener((()=>{t.disconnect()}))):Cn((()=>e.disconnect()),1)},keepAlive:e=>{const t=Co("keepAlive");t?(t.onMessage.addListener((t=>{e.postMessage(t)})),t.onDisconnect.addListener((()=>{e.disconnect()})),e.onMessage.addListener((e=>{t.postMessage(e)})),e.onDisconnect.addListener((()=>{
t.disconnect()}))):Cn((()=>e.disconnect()),1)}}),Ao=Et({setTimeout:({args:e,cb:t})=>{Cn(t,e.t)},setClipboard:({args:e,cb:t})=>{const{content:n,info:o,uuid:s}=e;let r,i;"object"==typeof o?(o.type&&(r=o.type),o.mimetype&&(i=o.mimetype)):"string"==typeof o&&(r=o);const a=i||("html"==r?"text/html":"text/plain");_n.document.addEventListener("copy",(e=>{e.stopImmediatePropagation(),e.preventDefault(),e.clipboardData&&e.clipboardData.setData(a,n)}),Et({capture:!0,once:!0})),
_n.document.execCommand("copy"),t()},closeTab:({args:{uuid:e},cb:t})=>{wo.sendMessage(Et({method:"closeTab",uuid:e,id:jo}),(e=>{e&&e.error&&Do.warn(e.error),t(e)}))},focusTab:({args:{uuid:e},cb:t})=>{wo.sendMessage(Et({method:"focusTab",uuid:e,id:jo}),(e=>{e&&e.error&&Do.warn(e.error),t(e)}))},addElement:async({args:t,node:n,cb:o})=>{try{const s=zn(t.tag,Et({...t.properties||Et({}),...t.id?Et({id:t.id}):Et({})}));let r,i;if("script"===t.tag&&(r=oo())&&s.setAttribute("nonce",r),n)i=n;else{
const t=_n.document;if(i=t.head||t.body||t.documentElement,!i){const t=_n.document;i=await bn((n=>e((()=>n(t.head||t.body)))))}}i.appendChild(s),r&&s.removeAttribute("nonce"),o()}catch(e){Do.warn("content: error adding script",e)}},tabs:({args:e,cb:t})=>{e.method="tabs",wo.sendMessage(e,(e=>e&&t(e.data)))},cookie:({args:e,cb:t})=>{e.method="cookie",wo.sendMessage(e,(e=>e&&t(e.data)))}}),To=Et({init:()=>{jo=twod.contextId},processMessage:({method:e,args:t,node:n},o)=>{let s
;if(s=Ao[e])return s(Et({args:t,node:n,cb:o}));o()},processConnect:(e,t)=>{let n;if(n=$o[e])return n(t)}}),Uo=["GM_info","GM.info"],ko=["unsafeWindow",...Uo],Bo=e=>e.replace(new RegExp("[\"']","g"),"\\$1");let Fo=!1;const Xo=(e,t,n,o,s)=>{const{console:r}=twod;Fo=Fo||e.logLevel>=60;const{version:i,injectMode:a,inIncognitoContext:c,isFirstPartyIsolation:d,downloadMode:l,relaxedCsp:u,userAgent:p,container:m,logLevel:g}=e,f=Et({version:i,injectMode:a,inIncognitoContext:c,isFirstPartyIsolation:d,
downloadMode:l,relaxedCsp:u,container:m});Ut(t,(async t=>{const{script:i,storage:a}=t,{name:c,uuid:d,options:{run_at:l}}=i,{requires:u,...m}=i,_=u.length,h=!i.options.unwrap,v=Et({...f,userAgent:p,logLevel:g,sandboxMode:s});let w,b;const y=((e,t)=>{const{measure_scripts:n,top_level_await:o,enforce_strict_mode:s}=e,{source_url:r,script:i,code:a}=t,{name:c,grant:d}=i,{requires:l}=i,u=!i.options.unwrap,p=l.map((e=>e.textContent||"")).join("\n");if(u){let e=""
;const t=["define","module","exports"],l=t.map((()=>"undefined")),u=-1!==i.grant.indexOf("none");let m;return m=u?Uo:d.concat(ko),m.forEach((e=>{const n=e.split(".")[0];"window"!==n&&-1===t.indexOf(n)&&(t.push(n),l.push(`p.${n}`))})),
[`with (${u?"this.s":"this"}) {`,"(async (u, { p, r, s }) => {","try {",n?`console.time("${e=`SCRIPT RUN TIME[${Bo(c)}]`}");\n`:"","r(u, s, [",l.join(","),"]);",n?`console.timeEnd("${e}");\n`:"","} catch (e) {","if (e.message && e.stack) {","console.error(\"ERROR: Execution of script '",Bo(c),"' failed! \" + e.message);","console.log(e.stack);","} else {","console.error(e);","}","}","})","(",(o?"async ":"")+"function(",t.join(","),") {",s?'"use strict";\n':"\n",p,a,"\n",`}, ${u?"this":"seed"})`,"}","\n",r?`//# sourceURL=${r}\n`:""].join("")
}return[p,a,"\n",r?`//# sourceURL=${r}\n`:""].join("")})(e,t);return h?(w=()=>{Fo&&r.debug(`env: inject "${c}" now`);const e=`__f__${yn()}`,t=Et({storage:a,script:m}),s=`window["${e}"] = function(){${y}}`;let i=!0;o.once(`scriptack-${e}`,(()=>{Fo&&!i&&r.log(`env: execution of "${c}" was delayed`),n(s,(e=>{e&&r.error(`Uncaught SyntaxError: ${e}`)}))})),o.send("script",Et({id:e,unwrap:!1,bundle:t,flags:v})),i=!1},b="context-menu"==l||"document-start"==l?void 0:()=>{
Fo&&r.debug(`env: run "${c}" now  (${_} requires)`),o.send("run",Et({uuid:d}))}):b=()=>{Fo&&r.debug(`env: inject @unwrap "${c}" now`),n(y,(e=>{e&&r.error(`Uncaught SyntaxError: ${e}`)}))},No(c,l,w,b,Fo)}))},No=(t,n,o,s,r)=>{const{console:i}=twod;let a;"document-start"==n?(r&&i.debug(`env: run "${t}" ASAP -> document-start`),a=e=>e()):"document-body"==n?(r&&i.debug(`env: schedule "${t}" for document-body`),
a=Vn):"context-menu"==n?r&&i.debug(`env: run "${t}" ASAP -> context-menu`):"document-end"==n?(r&&i.debug(`env: schedule "${t}" for document-end`),a=t=>e(!1,t)):(r&&i.debug(`env: schedule "${t}" for document-idle`),a=Zn),o&&o(),s&&a&&a((()=>{s()}))},qo=(e,t)=>{let n,o;try{o=(0,eval)(e)}catch(e){n=e.message||e}return t&&t(n),o},Wo=function(e,t,n,o,s){let r;const i=oo(),a=zn("script");i&&a.setAttribute("nonce",i);try{a.textContent=t,e.appendChild(a)}catch(e){r=e.message||e}
if(i&&a.removeAttribute("nonce"),!s){const e=a.parentNode;e&&e.removeChild(a)}return o&&o(r),!r},Ho=(e,t)=>{try{Wo(Nn.head||Nn.body||Nn.documentElement||Nn,e,0,t)}catch(e){t&&t(e.message||e)}};let Jo=!1;const Ko=location.pathname+location.search;vo.short_id,window.btoa(Ko.length+Ko).substr(0,255).replace(/[#=/]/g,"_");let Go=!1;const Yo=(t,n,o)=>{const{contextId:s,bridges:r,console:i}=twod;let a;bn((e=>{const o=t=>{let n=1;const o=()=>{Jo&&i.log('content: send "prepare" message'),
wo.sendMessage({method:"prepare",id:s,topframe:An,url:window.location.href},(s=>{if(!Go){if(!s)return Jo&&i.log("content: _early_ execution, connection to bg failed -> retry!"),window.setTimeout(o,n),void(n=yt(2*n,3e3));Go=!0,s.nonce&&no(s.nonce),ut(s.contexters).length||ut(s.scripts).length||s.external_connect?(t&&t(s),e({info:s,type:"complete"==Zt(_n.document)?"late":"normal"})):e({info:s})}}))};!function(e){const t=()=>"prerender"!==document.webkitVisibilityState,n=()=>{
t()&&(document.removeEventListener("webkitvisibilitychange",n,!1),e())};t()?e():document.addEventListener("webkitvisibilitychange",n,!1)}(o)},r=()=>{let r;if(Jo&&i.log("content: Started ("+s+", "+window.location.origin+window.location.pathname+")",hn.tm_info),r=hn.tm_info){delete hn.tm_info,r.nonce&&no(r.nonce);const{contexters:o,scripts:i,external_connect:c}=r;if(ut(o).length||ut(i).length||c){
if(r.contexters.raw||r.scripts.raw)if(t.raw)void 0===a&&(a=t.raw());else if(!n)throw"raw inject missing";e({info:r,type:"sync"})}else e({info:r});{let e;if("userscripts-dynamic"===r.contentMode){const t=e={};Ut(ut(i),(e=>{const n=i[e];n&&Ut(n,(({script:{uuid:e,name:n}})=>t[e]=n))}))}wo.sendMessage({method:"prepare",id:s,topframe:An,url:window.location.href,scripts:e,cleanup:!0},(()=>null))}}else n?o((({scripts:e,contexters:n})=>{t.raw&&void 0===a&&(e.raw||n.raw)&&(a=t.raw())
})):(t.raw&&void 0===a&&(a=t.raw()),o())};n?window.setTimeout((()=>r()),1):r()})).then((({info:a,type:c})=>{const{external_connect:d}=a;if(d&&(async()=>{await null,r.first.send("external.connect")})(),c){Jo=Jo||a.logLevel>=60;const{scripts:d}=a;if(d.raw){let e;n&&!t.raw&&(e=!0),e&&(t.js?(d.js=(d.js||[]).concat(d.raw||[]),delete d.raw):t.dom&&(d.dom=(d.dom||[]).concat(d.raw||[]),delete d.raw))}if(d.js){if(!t.js)throw"js inject missing";t.js()}if(d.dom){if(!t.dom)throw"dom inject missing";t.dom()}
e(!1,(()=>{Jo&&i.log("content: DOMContentLoaded"),Ut(ut(r),(e=>r[e].send("DOMContentLoaded")))})),l=()=>{Jo&&i.log("content: load"),Ut(ut(r),(e=>r[e].send("load")))},"complete"==Zt(_n.document)?l():wn.addEventListener("load",(()=>l()),Et({capture:!0,once:!0}));const u=(d.dom||[]).length+(d.js||[]).length+(d.raw||[]).length;Jo&&i.log("content: "+(c||"normal")+" start event processing for "+s+" ("+u+" to run)"),zo(a,"sync"===c),!An&&u&&window.addEventListener("unload",(()=>{wo.sendMessage({
method:"unLoad",id:s,topframe:!1,url:window.location.href},(()=>null))}),!1),o()}else o();var l}))},zo=e=>{const{bridges:t}=twod,{scripts:n,...o}=e;n.js&&Xo(o,n.js,So,t.js,"js"),n.dom&&(Ut(co,(e=>hn[e]=void 0)),Xo(o,n.dom,qo,t.dom,"dom")),n.raw&&Xo(o,n.raw,Ho,t.raw,"raw")};let Vo;(async()=>{const{unsafeWindow:e,bridges:o}=twod,{location:s,document:r}=e,i=r instanceof XMLDocument;if(!Et({"http:":!0,"https:":!0,"file:":!0})[e.location.protocol])return
;const a=twod.contextId?twod.contextId:twod.contextId=yn();let c;const d=Et({});mt(twod.console,Dn),bn((t=>{if(Eo){const{createBridge:e}=Ro(a);At(xo,((n,s)=>{Vo=c=n;const{modes:r}=s;r.js&&(o.js=e(),d.js=()=>!1,i&&(r.raw=!1)),t(s)}))}else bn((t=>{Vo=c=e.pagejs,delete e.pagejs,Vo?t():(()=>{let e=n=>{delete _n.pagejs,e=void 0,(e=>{if(!e)throw"Error: pagejs missing. Please see http://tmnk.net/faq#Q208 for more information.";Vo=c=e,t()})(n)};gt(_n,"pagejs",Et({set:e,configurable:!0})),Cn((()=>{e&&e()
}),1)})()})).then((()=>{t(Et({modes:Et({js:!1,raw:!0,dom:!0})}))}))})).then((({modes:{dom:r,raw:l},answer:u})=>{var p;if(u&&(p=u).scripts&&p.contexters&&(hn.tm_info=u),r){const e=Eo?qo(`() => ${c};`)():c,{createBridge:t,inject:n}=((e,t)=>{const n=(e,t)=>{Ut(s,(n=>n(e,t)))},o=e=>At(r,Et({listener:e,clone:e=>e})),s=[],r=[],i=(e,t)=>{Ut(r,(({listener:n,clone:o})=>n(e,o(t))))},a=e=>At(s,e),c="c"+yn();let d;return Et({createBridge:()=>(d=yo(Et({sendPrefix:"2S",listenPrefix:"2U",send:i,onMessage:a})),
d.init(e),d),inject:()=>(t(Et({unsafeWindow:_n,unsafeThis:hn,pageWindow:void 0,contextId:c,fSend:n,fOnMessage:o})),d.sendToId(c,"commid",Et({id:e})),!0)})})(a,e);d.dom=n,o.dom=t()}if(l){const{createBridge:e,inject:s}=((e,o)=>{let s;return Et({createBridge:()=>(s=(({sendPrefix:e,listenPrefix:t,cloneInto:o})=>{const s=e=>o?o(e,_n.document):e,r=Et({});let i,a,c=1;const d=Et({});let l=!1,u=[];const p=()=>{v=_n.document.documentElement,l=!1;const e=u;u=[],Ut(e,(e=>{l||b()?At(u,e):e()}))};let m
;const g=e=>{const t=++c;return d[c]=e,t},f=(e,t)=>{const{m:n,a:o,r,n:i}=t,{m:a,c}=((e,t,n)=>{let o,r;return n?(r=new cn(e,Et({relatedTarget:n})),o=new an(e,Et({detail:s(t)}))):o=new an(e,Et({detail:s(t)})),Et({m:r,c:o})})(e,Et({m:n,a:o,r}),i);a&&Mt(Ue,_n,[a]),Mt(Ue,_n,[c])},_=t=>{const n=(e=>{if("MouseEvent"===(e=>{const t=Bt(Xt(e)," ");return Ft($t(Ct(t,1)," "),0,-1)})(e)){const t=tn(e);if(!t)throw"Invalid MouseEvent";return void(m=t)}const t=qt(nn(e));return m&&(t.n=m,m=void 0),t})(t)
;if(!n)return;const{m:o,r:s,a:c,n:l}=n;if(r[o]&&(Ut(r[o],(e=>e(c))),delete r[o]),"unlock"==o)f(`${e}_${a}`,Et({m:"unlocked",a:void 0,r:null})),p();else if("unlocked"==o)p();else if("message.response"==o){if(null==s)throw"Invalid Message";((e,t)=>{let n;e&&(n=d[e])&&(n(t),delete d[e])})(s,c)}else if(i){const t=s?t=>{f(`${e}_${a}`,Et({m:"message.response",a:t,r:s}))}:()=>{};i(Et({method:o,args:c,node:l}),t)}},h=e=>{e&&(a=e),a&&wn.addEventListener(`${t}_${a}`,_,!0)};let v,w;const b=()=>{if((()=>{
const e=_n.document.documentElement;return v||(v=e),v!==e})()){if(w){const e=w;w=void 0,e(_n.document)}return!0}},y=Et({init:async(t,o)=>{a?h():h(t),(e=>(v=_n.document.documentElement,bn((async t=>{if(w=t,n&&!e&&(await null,b()))return;const o=new ln((()=>{b()&&o.disconnect()}));o.observe(_n.document,Et({childList:!0}))}))))(o).then((()=>{l=!0,y.refresh(),f(`${e}_${a}`,Et({m:"unlock",a:void 0,r:null}))}))},refresh:()=>{const e=a;e&&(y.cleanup(),y.init(e,!0))},switchId:e=>{a&&y.cleanup(),h(e)},
send:(t,n,o,s)=>bn((r=>{let i,c;"function"!=typeof o&&null!==o?(i=o,c=s):c=o,b();const d=()=>{f(`${e}_${a}`,Et({m:t,a:n,r:c?g(c):null,n:i})),r()};l?At(u,d):d()})),sendToId:(t,n,o)=>{f(`${e}_${t}`,Et({m:n,a:o,r:null}))},setMessageListener:e=>{i=e},once:(e,t)=>{r[e]||(r[e]=[]),At(r[e],t)},cleanup:()=>{a&&(wn.removeEventListener(`${t}_${a}`,_,!0),a=void 0)}});return y})(Et({sendPrefix:"2P",listenPrefix:"2C",cloneInto:Kn})),s),inject:()=>{s.init(e);let n=!1;const r=yn(),i="("+Wt(((e,t)=>{
const n=window,o=t(n),s=n.parent,{O_dPy:r,cSO:i}=o;r(s,e,i({value:o,enumerable:!1,writable:!1,configurable:!0}))}))+')("'+r+'", '+Wt(t)+")";return s.once("ack",(()=>{n=!0})),(t=>{((e,t)=>{const n=pn(en(_n.document,"*"),0)||_n.document,o=zn("div"),s=o.attachShadow(Et({mode:"closed"}));s.appendChild(zn("style",":host { display: none }"));const r=zn("iframe",Et({sandbox:"allow-scripts allow-same-origin",style:"display: none",src:"javascript:void 0"}));let i=()=>{if(null===i)return;i=null;let n=!1
;try{const t=r.contentDocument,o=r.contentWindow;t&&o&&(n=Wo(pn(t.getElementsByTagName("*"),0),e))}catch(e){}t(o,n),r.remove(),o.remove()};r.addEventListener("load",i,Et({once:!0,capture:!0})),s.appendChild(r),n.appendChild(o),i&&i()})(t,((t,n)=>{Wo(t,`(${o})({ unsafeWindow: typeof globalThis === "undefined" ? window : globalThis, unsafeThis: window, vault: ${n?`window["${r}"]`:"null"}, contextId: "${r}", __proto__: null });delete window["${r}"]\n`,0,(()=>{s.sendToId(r,"commid",Et({id:e}))}),!0)
}))})(i),n}})})(a,c);d.raw=s,o.raw=e()}o.first=o.js||o.raw||o.dom,wo.onMessage.addListener(((t,n,r)=>{"executeScript"==t.method?(t.url&&0!==Yt(s.href,t.url)||void 0!==t.topframe&&t.topframe!=An||zo(t.info,!1),r(Et({}))):An&&("loadUrl"==t.method?(e.location=t.url,r(Et({}))):"reload"==t.method?(s.reload(),r(Et({}))):"setForeignAttr"==t.method?(o.first.send(t.method,t),r(Et({}))):Dn.log("content: unknown method "+(e=>{const t=(e,n)=>{let o;if(null===e)o="null";else{const i=typeof e
;if("object"===i){if(n){if(-1!=Tt(n,e))throw"Converting circular structure to JSON";Lt(n,n.length,e)}else n=[e];if(vt(e)){let i="";for(let o=0;o<e.length;o++){let a;a=kt(e,o)?kt(s=e,r=o)?s[r]:void 0:It(e,o);const c=t(a,n);i+=`${o?",":""}${void 0===c?"null":c}`}o=`[${i}]`}else{let s="";Ut(ut(e),(o=>{const r=t(e[o],n);void 0!==r&&(s+=`${s?",":""}${O(o)}: ${r}`)})),o=`{${s}}`}n.length-=1}else{if("bigint"===i)throw"Do not know how to serialize a BigInt";o=O(e)}}var s,r;return o};return t(e)})(t)))
})),Mn.onConnect.addListener(((e,t)=>{To.processConnect(e,t)})),To.init(),Ut(ut(o),(e=>{if("first"==e)return;const t=o[e];t.setMessageListener(((n,o)=>{const{method:s,args:r}=n;if("port.message"==s)Mn.message(r,t);else if("csp"==s){let t;t="raw"==e?Ho:"dom"==e?qo:So,t(r.src,(e=>{e&&Dn.error(`Uncaught Error: ${e}`)}))}else if("external.message"==s)wo.sendMessage(Et({method:"externalMessage",request:r}),(e=>{o(e)}));else if("console"==s){const e=r,t=pn(e,0),n=pn(e,1),o=Dn[t]||Dn.log
;o&&Mt(o,Dn,((e,...t)=>{let n=e.length;const o=Et(e);for(let e=0;e<t.length;e++){const s=t[e],r=vt(s)?s:[s];for(let e=0;e<r.length;e++)o[n+e]=St(r,e);n+=r.length}return pt(o)})(["injected:"],(e=>{const t=[];return Ut(e,(e=>{At(t,(e=>"string"==typeof e?jt(e):e)(e))})),t})(n)))}else To.processMessage(n,o)}))})),Yo(d,i,(()=>Vo=void 0)),(async()=>{const{contextId:e}=twod,{location:t,document:n}=_n;n.addEventListener("mouseenter",(()=>{wo.sendMessage(Et({method:"contextmenu",url:t.href,id:e
}),(()=>{}))}),!1)})()}))})()})();})({ __proto__: null, unsafeWindow: typeof globalThis === "undefined" ? window : globalThis, unsafeThis: window, }, "tm_hgyips")